import Zeta

x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1 = Zeta.Panel.Window(color2='green', title='asdasdasdasd')
x1.mainloop()