#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Jul 31, 2023 02:07:09 AM +07  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import unknown_support

_bgcolor = '#ffffff'  # X11 color: 'white'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x428+159+129")
        top.minsize(112, 1)
        top.maxsize(1366, 724)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#ffffff")

        self.top = top
        self.menuSelectedButton = tk.StringVar()
        self.checks_1 = tk.StringVar()

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.menubar.add_command(compound='left',label='NewCommand')
        self.menubar.add_command(compound='left',label='NewCommand')
        self.menubar.add_separator()
        self.menubar.add_radiobutton(value='NewRadio'
                ,variable=self.menuSelectedButton, compound='left'
                ,label='NewRadio')
        self.menubar.add_checkbutton(variable=self.checks_1, compound='left'
                ,label='NewCheck')
        self.sub_menu = tk.Menu(self.menubar, activebackground='beige'
                ,activeborderwidth=1, activeforeground='black'
                ,background='#ffffff', borderwidth=1, disabledforeground='#bfbfbf'
                ,foreground='#000000', tearoff=0)
        self.menubar.add_cascade(compound='left', label='NewCascade'
                ,menu=self.sub_menu, )
        self.sub_menu.add_command(compound='left',label='NewCommand')
        self.sub_menu.add_command(compound='left',label='NewCommand')
        self.sub_menu.add_separator()

def start_up():
    unknown_support.main()

if __name__ == '__main__':
    unknown_support.main()




