#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Jun 27, 2023 11:10:10 AM +07  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 912x710+0+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1366 746
    wm minsize $top 112 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Zeta Lockhart | Proxy"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::separator "$top.tSe47" \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe47" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    labelframe "$top.lab49" \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) -text "Proxy" \
        -background #ffffff -height 76 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 419 
    vTcl:DefineAlias "$top.lab49" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.lab49
    label "$site_3_0.lab51" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #ffffff -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Web" 
    vTcl:DefineAlias "$site_3_0.lab51" "Label3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab52" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #ffffff -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #ff8000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "https://www.proxysite.com/" 
    vTcl:DefineAlias "$site_3_0.lab52" "Label4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.024 -y 0 -rely 0.263 -width 0 \
        -relwidth 0.081 -height 0 -relheight 0.276 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.12 -y 0 -rely 0.263 -width 0 \
        -relwidth 0.56 -height 0 -relheight 0.276 -anchor nw \
        -bordermode ignore 
    labelframe "$top.lab50" \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) -text "VPN" \
        -background #ffffff -height 76 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 419 
    vTcl:DefineAlias "$top.lab50" "Labelframe1_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.lab50
    label "$site_3_0.lab48" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #ffffff -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "MS-SSTP" 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab49" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #ffffff -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #ff8000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "https://www.vpngate.net/en/" 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.024 -y 0 -rely 0.263 -width 0 \
        -relwidth 0.129 -height 0 -relheight 0.276 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.168 -y 0 -rely 0.263 -width 0 \
        -relwidth 0.705 -height 0 -relheight 0.276 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tSe47 \
        -in $top -x 0 -relx 0.504 -y 0 -rely 0.028 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.945 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.014 -width 0 -relwidth 0.458 \
        -height 0 -relheight 0.107 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.526 -y 0 -rely 0.014 -width 0 -relwidth 0.458 \
        -height 0 -relheight 0.107 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

